### PR TITLE
ci: replace docker image to solve eureka server response-cache-update…

### PR DESCRIPTION
**Pull request by codingxh**
en: Replace docker image to solve the problem that the service discovery after service registration in unit testing and the instance list is delayed by 30s
zh: 替换docker镜像去解决单元测试中服务注册后进行服务发现拉取实例列表延迟30s的问题

### CODE REVIEW

**Review by li-jin-gou — APPROVED** [review]
Good Job!

**Comment by li-jin-gou** [comment]
@codingxh  hello, Push Check failed.:smile:

**Comment by GuangmingLuo** [comment]
TestEurekaDiscoveryWithMultipleInstance UT failed, but why ? @li-jin-gou

**Comment by codingxh** [comment]
already have a problem , sorry , i will retry a new mr

**Pull request closed without merging**
